#!/usr/bin/env bash
# Builds the Windows installer for the editor app (dist/windows/
# Markdown-Cornell-Notes-Setup-<version>.exe, an NSIS per-user installer),
# bundling Python (the official embeddable build), Qt (PySide6), pandoc,
# and TeX so the user installs nothing else. See scripts/bundle_common.sh
# for what the bundle holds and how it's put together.
#
# Runs on an x86_64 Linux host -- no Windows needed: every piece is a
# prebuilt download, and NSIS's compiler (makensis) runs on Linux, from
# the host if it's installed there, else in a container (podman or
# docker).
#
# The installed app has no .exe of its own: its shortcuts start the
# bundled pythonw.exe (Python without a console window) on app/main.py.
#
# Usage: scripts/build_windows.sh   (or `make windows`)
set -euo pipefail
# shellcheck source=bundle_common.sh
source "$(dirname "$0")/bundle_common.sh"

STAGE="$ROOT/dist/windows-stage"
RES="$STAGE/resources"
OUT="$ROOT/dist/windows"
NSIS_IMAGE="docker.io/library/debian:trixie-slim" # only used without a makensis on the host

download "https://github.com/jgm/pandoc/releases/download/$PANDOC_VERSION/pandoc-$PANDOC_VERSION-windows-x86_64.zip" \
  "$CACHE/pandoc-$PANDOC_VERSION-windows.zip"
download "https://www.python.org/ftp/python/$PYTHON_VERSION/python-$PYTHON_VERSION-embed-amd64.zip" \
  "$CACHE/python-$PYTHON_VERSION-embed.zip"
prepare_build_python
prepare_tex

echo "Staging resources..."
rm -rf "$STAGE"
mkdir -p "$RES"/{pipeline,python,pandoc}

stage_texlive "$RES/texlive" windows
stage_pipeline "$RES/pipeline"
stage_dictionary "$RES"

unzip -q -j "$CACHE/pandoc-$PANDOC_VERSION-windows.zip" \
  "pandoc-$PANDOC_VERSION/pandoc.exe" "pandoc-$PANDOC_VERSION/COPYRIGHT.txt" "pandoc-$PANDOC_VERSION/COPYING.rtf" \
  -d "$RES/pandoc"

unzip -q "$CACHE/python-$PYTHON_VERSION-embed.zip" -d "$RES/python"
# tzdata: Windows has no system time zone database for zoneinfo to read.
stage_pyside "$RES/python/Lib/site-packages" win_amd64 "tzdata==$TZDATA_VERSION"
# The embeddable build's ._pth file replaces sys.path outright -- so it
# includes neither site-packages nor the running script's own directory,
# which app/ and scripts/ need to import their own modules. Add all three
# (relative to python.exe).
pth=("$RES"/python/python*._pth)
printf '%s\r\n' 'Lib\site-packages' '..\pipeline\app' '..\pipeline\scripts' >> "${pth[0]}"

cp "$ROOT/LICENSE" "$STAGE/LICENSE.txt"
cp "$ROOT/app/build-resources/icon.ico" "$STAGE/icon.ico"
write_notices "$RES/THIRD-PARTY-NOTICES.txt" "embeddable distribution" "python/LICENSE.txt"

installer="Markdown-Cornell-Notes-Setup-$APP_VERSION.exe"
# Quoted heredoc: NSIS's own $VARIABLES pass through; the two values the
# script needs from here come in as /D defines on makensis's command line.
cat > "$STAGE/installer.nsi" <<'EOF'
; Per-user installer for Markdown Cornell Notes (generated by
; scripts/build_windows.sh): no administrator rights needed.
Unicode true
SetCompressor /SOLID lzma
!include "MUI2.nsh"

!define APP_NAME "Markdown Cornell Notes"
!define UNINSTALL_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\io.github.forloop11.markdown-cornell-notes"
; The app is Python: its shortcuts run the bundled interpreter on main.py.
!define APP_EXE "$INSTDIR\resources\python\pythonw.exe"
!define APP_ARGS "$\"$INSTDIR\resources\pipeline\app\main.py$\""

Name "${APP_NAME}"
OutFile "${OUT_FILE}"
RequestExecutionLevel user
InstallDir "$LOCALAPPDATA\Programs\${APP_NAME}"
InstallDirRegKey HKCU "${UNINSTALL_KEY}" "InstallLocation"

!define MUI_ICON "icon.ico"
!define MUI_UNICON "icon.ico"
!define MUI_FINISHPAGE_RUN "${APP_EXE}"
!define MUI_FINISHPAGE_RUN_PARAMETERS "${APP_ARGS}"
!insertmacro MUI_PAGE_LICENSE "LICENSE.txt"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "Install"
  SetOutPath "$INSTDIR"
  File "LICENSE.txt"
  File "icon.ico"
  File /r "resources"
  WriteUninstaller "$INSTDIR\Uninstall.exe"

  CreateShortcut "$SMPROGRAMS\${APP_NAME}.lnk" "${APP_EXE}" "${APP_ARGS}" "$INSTDIR\icon.ico"
  CreateShortcut "$DESKTOP\${APP_NAME}.lnk" "${APP_EXE}" "${APP_ARGS}" "$INSTDIR\icon.ico"

  WriteRegStr HKCU "${UNINSTALL_KEY}" "DisplayName" "${APP_NAME}"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "DisplayVersion" "${APP_VERSION}"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "Publisher" "Todd C. Takala"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "DisplayIcon" "$INSTDIR\icon.ico"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "UninstallString" '"$INSTDIR\Uninstall.exe"'
  WriteRegDWORD HKCU "${UNINSTALL_KEY}" "NoModify" 1
  WriteRegDWORD HKCU "${UNINSTALL_KEY}" "NoRepair" 1
SectionEnd

; Removes the program only: notes live in Documents\Cornell Notes (or
; wherever the user keeps them), which this never touches.
Section "Uninstall"
  Delete "$SMPROGRAMS\${APP_NAME}.lnk"
  Delete "$DESKTOP\${APP_NAME}.lnk"
  RMDir /r "$INSTDIR\resources"
  Delete "$INSTDIR\LICENSE.txt"
  Delete "$INSTDIR\icon.ico"
  Delete "$INSTDIR\Uninstall.exe"
  RMDir "$INSTDIR"
  DeleteRegKey HKCU "${UNINSTALL_KEY}"
SectionEnd
EOF

echo "Building the installer (compressing takes a few minutes)..."
rm -rf "$OUT"
mkdir -p "$OUT"
nsis_args=(-V2 "-DAPP_VERSION=$APP_VERSION" "-DOUT_FILE=../windows/$installer" installer.nsi)
if command -v makensis > /dev/null; then
  (cd "$STAGE" && makensis "${nsis_args[@]}")
else
  container="${CONTAINER:-$(command -v podman || command -v docker || true)}"
  if [ -z "$container" ]; then
    echo "Needs makensis (NSIS), or podman or docker to run it in $NSIS_IMAGE." >&2
    exit 1
  fi
  # label=disable: on SELinux hosts (e.g. Fedora), lets the container read
  # the bind mount without relabeling the checkout.
  "$container" run --rm --security-opt label=disable -v "$ROOT/dist":/dist -w /dist/windows-stage "$NSIS_IMAGE" \
    sh -c 'apt-get -qq update && apt-get -qq install -y nsis > /dev/null && makensis "$@"' sh "${nsis_args[@]}"
fi

ls -lh "$OUT"/*.exe
